### PR TITLE
Merge DPS toolkit changes from IBM Streams 4.2.1.0

### PR DESCRIPTION
**Pull request by brandtol**
The toolkit version is updated to 3.1.0
Overview of changes:

- Setting DPS config at runtime (pull request #24)
- Add Translation
- Bugfix: key/value data allocated with malloc() should be released
  with free(), not delete []
- Implemented dpsPersist for RedisClusterDBLayer
- Add DPSAux operator
- Change to manually load libraries and their dependencies
  to support Java
- Update samples and documentation
- Update DPS dependencies: aerospike, cassandra, couchbase, curl, 
  hiredis, mongo and uv
- Add couchbase and aerospike libraries to DPS toolkit

### CODE REVIEW

**Comment by ZollnaPa** [comment]
If you merge this version then remember to update the README.md with the link to NLS description:
[The messages and the NLS for toolkits](https://github.com/IBMStreams/administration/wiki/Messages-and-National-Language-Support-for-toolkits)

**Comment by natashadsilva** [comment]
@nysenthil  can you please take a look and merge? 
@brandtol This file no longer exists in the proposed merge:  https://github.com/IBMStreams/streamsx.dps/blob/master/com.ibm.streamsx.dps/samples/dps_test_1/etc/no-sql-kv-store-servers.cfg

This is okay since the samples have been moved into a separate folder, however the connection instructions for unsupported databases need to be put somewhere. I propose putting them on a Wiki page and editing the README.md for the repo to point to them.

**Comment by nysenthil** [comment]
Hi Natasha,
I discussed with Oliver Brandt this morning. He said he will merge it by himself when he comes to work tomorrow and proceed from there.

**Comment by brandtol** [comment]
@natashadsilva I think these instructions are still in the conf file under extraSamples/DPSFunctionDemo , not sure if these are the same. Having them in the Wiki is a good idea. I will add a page and update the README.

**Pull request merged**
